### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by ss2299** [Python-beyond-Vision/P4#1]
## Python

print('p4 function is available with us')

**Comment by ss2299** [comment]
test @Matthew-kim-engineer

**Comment by Matthew-kim-engineer** [comment]
> ## Python
> print('p4 function is available with us')

print('Matthew not agree of that')

**Comment by Matthew-kim-engineer** [comment]
> test @Matthew-kim-engineer

glad to see you

**Comment by ss2299** [comment]
@Matthew-kim-engineer 한글로 해도 됨.. ㅎ
